// swift-tools-version:5.9
// This file is automatically generated by the Gradle build.
// Do not edit manually - see backend/api/build.gradle.kts for the generation logic.
import PackageDescription

let package = Package(
    name: "FeastMultiplatformBackend",
    platforms: [
        .iOS(.v17),
    ],
    products: [
        .library(name: "FeastMultiplatformBackend", targets: ["FeastMultiplatformBackend"])
    ],
    targets: [
        .binaryTarget(
            name: "FeastMultiplatformBackend",
            url: "https://github.com/guardian/feast-multiplatform-backend/releases/download/2.0.1/FeastMultiplatformBackend.xcframework.zip",
            checksum:"34670e14d2aabc5ef570890c7b90cc942437d2cfe1ebe18a4601907b3f8765e1")
    ]
)