// swift-tools-version:5.9
// This file is automatically generated by the Gradle build.
// Do not edit manually - see backend/api/build.gradle.kts for the generation logic.
import PackageDescription

let package = Package(
    name: "FeastMultiplatformBackend",
    platforms: [
        .iOS(.v17),
    ],
    products: [
        .library(name: "FeastMultiplatformBackend", targets: ["FeastMultiplatformBackend"])
    ],
    targets: [
        .binaryTarget(
            name: "FeastMultiplatformBackend",
            url: "https://github.com/guardian/feast-multiplatform-backend/releases/download/0.0.1/FeastMultiplatformBackend.xcframework.zip",
            checksum:"973f233cfd28038001503c05f6d6d4870e4108253ac587d38f3fa5828ee9455b")
    ]
)