// swift-tools-version:5.9
// This file is automatically generated by the Gradle build.
// Do not edit manually - see backend/api/build.gradle.kts for the generation logic.
import PackageDescription

let package = Package(
    name: "FeastMultiplatformBackend",
    platforms: [
        .iOS(.v17),
    ],
    products: [
        .library(name: "FeastMultiplatformBackend", targets: ["FeastMultiplatformBackend"])
    ],
    targets: [
        .binaryTarget(
            name: "FeastMultiplatformBackend",
            url: "https://github.com/guardian/feast-multiplatform-backend/releases/download/0.0.2/FeastMultiplatformBackend.xcframework.zip",
            checksum:"29f6fb1f744e93ca216a0678e91c91a4fc2b1a57962bde6f2d732e22cfff7dc6")
    ]
)